a = int(input("please enter value of variable a:\n"))
b = int(input("please enter value of variable b:\n"))
res = a + b
print(a, '+', b, '=' , res)
res = a - b
print(a, '-', b, '=' , res)
res = a * b
print(a, '*', b, '=' , res)
res = a / b
print(a, '/', b, '=' , res)
