a = input("please insert value of variable a:\n")
b = input("please insert value of variable b:\n")
res = a + b
print(a, '+', b, '=' , res)
res = a - b
print(a, '-', b, '=' , res)
res = a * b
print(a, '*', b, '=' , res)
res = a / b
print(a, '/', b, '=' , res)